name: quizfirebase
description: Quiz Firebase Authentication App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9

  # Image picker untuk profile photo
  image_picker: ^1.0.7

  # Shared preferences untuk menyimpan theme preference
  shared_preferences: ^2.2.2

  # Provider untuk state management
  provider: ^6.1.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/