// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJndkQJBeGMNaHUa5A8jokpeg2HsQUU4w',
    appId: '1:78643822515:web:6f93f23f9261a2734595c6',
    messagingSenderId: '78643822515',
    projectId: 'quizfirebase-9fbd9',
    authDomain: 'quizfirebase-9fbd9.firebaseapp.com',
    storageBucket: 'quizfirebase-9fbd9.firebasestorage.app',
    measurementId: 'G-MQNJNQVG81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxcFqlMK1HeBNdRIIB2jiSKTkMeEZRfdo',
    appId: '1:78643822515:android:699d5a48907404764595c6',
    messagingSenderId: '78643822515',
    projectId: 'quizfirebase-9fbd9',
    storageBucket: 'quizfirebase-9fbd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLaDA2D2g0vPA939StU_7cCRTyfIGH4sw',
    appId: '1:78643822515:ios:dc00c2781199c85d4595c6',
    messagingSenderId: '78643822515',
    projectId: 'quizfirebase-9fbd9',
    storageBucket: 'quizfirebase-9fbd9.firebasestorage.app',
    iosBundleId: 'com.example.quizfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLaDA2D2g0vPA939StU_7cCRTyfIGH4sw',
    appId: '1:78643822515:ios:dc00c2781199c85d4595c6',
    messagingSenderId: '78643822515',
    projectId: 'quizfirebase-9fbd9',
    storageBucket: 'quizfirebase-9fbd9.firebasestorage.app',
    iosBundleId: 'com.example.quizfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJndkQJBeGMNaHUa5A8jokpeg2HsQUU4w',
    appId: '1:78643822515:web:d9492c709bb58db24595c6',
    messagingSenderId: '78643822515',
    projectId: 'quizfirebase-9fbd9',
    authDomain: 'quizfirebase-9fbd9.firebaseapp.com',
    storageBucket: 'quizfirebase-9fbd9.firebasestorage.app',
    measurementId: 'G-9487ZC9P1C',
  );
}
